name: 01 - Create HP database and seed it

on:
  workflow_dispatch

env:
  pscale_base_directory: .pscale

jobs:

  create-database:
    name: "Create database - click here"
    runs-on: ubuntu-latest
        
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Create database and seed it - please click on displayed link to authenticate
        timeout-minutes: 3
        env:
          PLANETSCALE_SERVICE_TOKEN_NAME: ${{secrets.PLANETSCALE_SERVICE_TOKEN_NAME}}
          ORG_NAME: ${{secrets.ORG_NAME}}
          DB_NAME: ${{secrets.DB_NAME}}
          GITHUB_USER: ${{github.actor}}
        working-directory: ${{env.pscale_base_directory}}/cli-helper-scripts/
        run: ./create-database-and-seed.sh